spring:
  datasource:
    password: namnamnam
    username: postgres
    url: jdbc:postgresql://localhost:5432/web_chat_v2?serverTimezone=UTC

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # SECURITY
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 123
            client-secret: 123
  # Server mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: dduymen@gmail.com
    password: vcuwqngagorsvitw
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 9090

# SWAGGER - http://localhost:9090/swagger-ui/index.html
open-api:
  service:
    api-docs: API documentss
    title: Chat-API
    version: v1.0.0
    server: http://localhost:9090


app:
  baseURL: http://localhost:${server.port}
  name: ChatChit
  jwt:
    secretKey: c3ckfrhaKW8Mplm9ylgQCsMLoFmsip/ouP1u51eWRLRtCgDA6OFoLH+azJtNEDUYODPqhm/Kms2jYJdaIczcrap9vBVrbd7qMk1AuoNJjZg=
    expiration-time-ms: 86400000 # 30 minutes
  tokenExpirationTimes:
    refresh: 86400000 # Refresh token expiration time (24 hours)
    registration: 900000 # Registration token expiration time (15 minutes)
    forgotPassword: 1800000 # Forgot password token expiration time (30 minutes)
    resetPassword: 1800000 # Reset password token expiration time (30 minutes)


  endpoint:
    security:
      verify-new-user: ${app.baseURL}/api/v1/auth/verify-new-user
      reset-password: ${app.baseURL}/api/v1/auth/reset-password